complete -c nix -x -a fix -d 'verify and repair store contents'
complete -c nix -x -a repkg -d 'build a package'
complete -c nix -x -a clean -d 'run nixos garbage collector'
complete -c nix -x -a search -d 'find a package'
complete -c nix -x -a upgrade -d 'apply the updated nixos configuration and switch upgrading in the process'
complete -c nix -x -a update -d 'apply the updated nixos configuration and switch'
complete -c nix -x -a install -d 'install a package'